version: '3.9'

services:
  database:
    image: postgres:latest
    networks:
      network:
        ipv4_address: 10.5.0.4
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=korean-cosmetic-shop
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - MAX_LOGIN_ATTEMPTS=0
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=password
    restart: unless-stopped
    networks:
      network:
        ipv4_address: 10.5.0.5
    depends_on:
      - database
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/root/.
  
  mvc-service:
    image: mvc-service
    networks:
      network:
        ipv4_address: 10.5.0.6
    ports:
      - "8080:8070"
    depends_on:
      - database
    environment:
      ASPNETCORE_URLS: http://+:8070
      
volumes:
  database-data:
  pgadmin:

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1